server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  application:
    name: halo-blog-production
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      location: /tmp/run.halo.app
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    run.halo.app: INFO
  file:
    path: ${user.home}/.halo/logs

halo:
  download-timeout: 5m
  cache: memory #hazelcast
  ##hazelcast configs##
  #hazelcastMembers: 127.0.0.1:22055 #127.0.0.1:5701 #10.4.5.100:5701,10.4.5.101:5701,10.4.5.102:5701
  #hazelcastGroupName: tt-mps-hz-cluster #halo-hz-cluster
  #initialBackoffSeconds: 5